"use client";
import { useState, type FormEvent } from "react";
import { demonstrationEmployees, type EmployeeCode } from "@/lib/domain/employees";
import { formatEuro } from "@/lib/domain/finance";
import type { DashboardTotals, ExpenseRecord, SaleRecord } from "@/lib/domain/types";
type Message = { kind: "success" | "error"; text: string } | null;
type ViewData = { role: string; sales: SaleRecord[]; expenses: ExpenseRecord[]; totals: DashboardTotals | null };
async function requestJson(url: string, method = "GET", body?: unknown) { const response = await fetch(url, { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined, cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Request failed."); return data; }
export function FinanceApp() {
 const [role,setRole]=useState<EmployeeCode|"">(""); const [message,setMessage]=useState<Message>(null); const [data,setData]=useState<ViewData|null>(null); const employee=demonstrationEmployees.find(i=>i.code===role);
 async function refresh(){setData(await requestJson("/api/dashboard"));}
 async function chooseRole(code:EmployeeCode){setMessage(null);setData(null);try{await requestJson("/api/demo-role","POST",{code});setRole(code);setData(await requestJson("/api/dashboard"));}catch(e){setMessage({kind:"error",text:e instanceof Error?e.message:"Could not select the role."});}}
 async function submit(event:FormEvent<HTMLFormElement>,endpoint:string){event.preventDefault();setMessage(null);const form=event.currentTarget;try{const result=await requestJson(endpoint,"POST",Object.fromEntries(new FormData(form).entries()));setMessage({kind:"success",text:`${result.reference} saved with status ${result.status.replaceAll("_"," ")}.`});form.reset();await refresh();}catch(e){setMessage({kind:"error",text:e instanceof Error?e.message:"The transaction could not be saved."});}}
 async function decide(event:FormEvent<HTMLFormElement>,endpoint:string){event.preventDefault();setMessage(null);try{const result=await requestJson(endpoint,"POST",Object.fromEntries(new FormData(event.currentTarget).entries()));setMessage({kind:"success",text:result.alreadyProcessed?`${result.reference} was already processed; nothing changed.`:`${result.reference} approved successfully.`});await refresh();}catch(e){setMessage({kind:"error",text:e instanceof Error?e.message:"Decision could not be saved."});}}
 async function managerAction(event:FormEvent<HTMLFormElement>,endpoint:string,success:string){event.preventDefault();setMessage(null);try{await requestJson(endpoint,"POST",Object.fromEntries(new FormData(event.currentTarget).entries()));setMessage({kind:"success",text:success});await refresh();}catch(e){setMessage({kind:"error",text:e instanceof Error?e.message:"The action failed."});}}
 const pendingSales=data?.sales.filter(s=>s.status==="PENDING_APPROVAL")??[]; const pendingExpenses=data?.expenses.filter(e=>e.status==="AWAITING_ALLOCATION")??[];
 return <main><header><p className="eyebrow">Friends Included Ltd</p><h1>Finance system</h1><p className="lede">Day 4 homework by Diāna Vasiļjeva. Submit transactions, make manager decisions, and view financial results.</p><p>Choose a <strong>Demonstration role</strong> below. Salespeople submit sales, Kevin submits expenses, and Svetlana reviews pending items and the dashboard.</p><p><a href="https://t.me/friends_included_diana_bot">Telegram bot</a> · <a href="https://docs.google.com/spreadsheets/d/1vIn9gpu334Neny5M3_8E1GzthfU0SKRBH35E4uxgsu4/edit">Google Sheets ledger</a> · <a href="https://github.com/DiaanaVa/friends-included-finance">GitHub repository</a></p></header>
 <section><h2>Demonstration role</h2><label htmlFor="role">Choose the employee whose permissions you want to test.</label><select id="role" value={role} onChange={e=>void chooseRole(e.target.value as EmployeeCode)}><option value="">Select an employee</option>{demonstrationEmployees.map(i=><option key={i.code} value={i.code}>{i.displayName}</option>)}</select>{employee&&<p className="role-note">Active role: <strong>{employee.displayName}</strong> ({employee.role.replace("_"," ")})</p>}</section>{message&&<p role="status" className={`message ${message.kind}`}>{message.text}</p>}
 {employee?.role==="salesperson"&&<section><h2>Submit a sale</h2><form onSubmit={e=>void submit(e,"/api/sales")}><label>Reference<input name="reference" placeholder="S01" required/></label><label>Customer<input name="customer" required/></label><label>Project<select name="project"><option value="A">A - Respectable Relatives</option><option value="B">B - Drunk University Friends</option></select></label><label className="wide">Description<textarea name="description" required/></label><label>Amount in euros<input name="amount" inputMode="decimal" required/></label><fieldset className="wide"><legend>Proposed commission split</legend><div className="split"><label>Richard %<input name="proposedRichardPct" type="number" step="0.01" required/></label><label>Anastasia %<input name="proposedAnastasiaPct" type="number" step="0.01" required/></label><label>Jean-Claude %<input name="proposedJeanClaudePct" type="number" step="0.01" required/></label></div></fieldset><button>Save pending sale</button></form></section>}
 {employee?.role==="expense_reporter"&&<section><h2>Submit an expense</h2><form onSubmit={e=>void submit(e,"/api/expenses")}><label>Reference<input name="reference" placeholder="E01" required/></label><label>Category<select name="category"><option>Materials</option><option>Travel</option><option>Other</option></select></label><label className="wide">Description<textarea name="description" required/></label><label>Amount in euros<input name="amount" inputMode="decimal" required/></label><label>Proposed allocation<select name="proposedAllocation"><option value="A">Project A</option><option value="B">Project B</option><option value="OVERHEAD">Company overhead</option></select></label><button>Save expense</button></form></section>}
 {employee?.role==="manager"&&data?.totals&&<><Dashboard totals={data.totals}/><section><h2>Link a Telegram account</h2><p>Ask the employee to send <code>/whoami</code> to the bot, then enter the displayed numeric ID.</p><form onSubmit={e=>void managerAction(e,"/api/telegram/link","Telegram account linked.")}><label>Employee<select name="code">{demonstrationEmployees.map(i=><option key={i.code} value={i.code}>{i.displayName}</option>)}</select></label><label>Telegram user ID<input name="telegramUserId" inputMode="numeric" required/></label><button>Link account</button></form></section><section><h2>Pending sales</h2>{!pendingSales.length&&<p>Nothing is waiting for approval.</p>}{pendingSales.map(s=><article className="card" key={s.id}><h3>{s.reference}: {s.customer}</h3><p>{s.description} · Project {s.project} · {formatEuro(s.amount_cents)}</p><p><strong>Original proposal:</strong> Richard {s.proposed_richard_pct}%, Anastasia {s.proposed_anastasia_pct}%, Jean-Claude {s.proposed_jean_claude_pct}%.</p><form onSubmit={e=>void decide(e,`/api/sales/${s.reference}/approve`)}><label>Richard %<input name="richardPct" type="number" step="0.01" defaultValue={s.proposed_richard_pct} required/></label><label>Anastasia %<input name="anastasiaPct" type="number" step="0.01" defaultValue={s.proposed_anastasia_pct} required/></label><label>Jean-Claude %<input name="jeanClaudePct" type="number" step="0.01" defaultValue={s.proposed_jean_claude_pct} required/></label><button>Approve sale</button></form></article>)}</section><section><h2>Expenses awaiting allocation</h2>{!pendingExpenses.length&&<p>Nothing is waiting for allocation.</p>}{pendingExpenses.map(e=><article className="card" key={e.id}><h3>{e.reference}: {e.description}</h3><p>{e.category} · {formatEuro(e.amount_cents)} · <strong>Original proposal:</strong> {e.proposed_allocation}</p><form onSubmit={event=>void decide(event,`/api/expenses/${e.reference}/allocate`)}><label>Final allocation<select name="allocation" defaultValue={e.proposed_allocation}><option value="A">Project A</option><option value="B">Project B</option><option value="OVERHEAD">Company overhead</option></select></label><button>Allocate expense</button></form></article>)}</section><IntegrationRecords sales={data.sales} expenses={data.expenses} retry={managerAction}/></>}
 {employee&&employee.role!=="manager"&&data&&<Records sales={data.sales} expenses={data.expenses}/>}</main>;
}
function Dashboard({totals}:{totals:DashboardTotals}){const rows=[["Project A income",totals.projectA.incomeCents],["Project A commissions",totals.projectA.commissionCents],["Project A expenses",totals.projectA.expensesCents],["Project A result",totals.projectA.resultCents],["Project B income",totals.projectB.incomeCents],["Project B commissions",totals.projectB.commissionCents],["Project B expenses",totals.projectB.expensesCents],["Project B result",totals.projectB.resultCents],["Company overhead",totals.company.overheadCents],["Awaiting allocation",totals.company.awaitingAllocationCents],["Total company result",totals.company.resultCents],["Richard commission",totals.commissionsByEmployee.richard],["Anastasia commission",totals.commissionsByEmployee.anastasia],["Jean-Claude commission",totals.commissionsByEmployee.jean_claude]] as const;return <section><h2>Financial dashboard</h2><div className="metrics">{rows.map(([l,v])=><div className="metric" key={l}><span>{l}</span><strong>{formatEuro(v)}</strong></div>)}<div className="metric"><span>Pending sales</span><strong>{totals.pendingSales}</strong></div><div className="metric"><span>Pending expense allocations</span><strong>{totals.pendingExpenseAllocations}</strong></div></div></section>}
function Records({sales,expenses}:{sales:SaleRecord[];expenses:ExpenseRecord[]}){return <section><h2>Your submitted records</h2>{sales.map(s=><p key={s.id}><strong>{s.reference}</strong> — sale, {formatEuro(s.amount_cents)}, {s.status.replaceAll("_"," ")} · Sheets {s.sheets_sync_status??"PENDING"} · Telegram {s.notification_status??"NOT REQUIRED"}</p>)}{expenses.map(e=><p key={e.id}><strong>{e.reference}</strong> — expense, {formatEuro(e.amount_cents)}, {e.status.replaceAll("_"," ")} · Sheets {e.sheets_sync_status??"PENDING"} · Telegram {e.notification_status??"NOT REQUIRED"}</p>)}{!sales.length&&!expenses.length&&<p>No submitted records yet.</p>}</section>}
function IntegrationRecords({sales,expenses,retry}:{sales:SaleRecord[];expenses:ExpenseRecord[];retry:(event:FormEvent<HTMLFormElement>,endpoint:string,success:string)=>Promise<void>}){const rows=[...sales.map(record=>({kind:"SALE",record})),...expenses.map(record=>({kind:"EXPENSE",record}))];return <section><h2>Integration status</h2>{!rows.length&&<p>No transactions yet.</p>}{rows.map(({kind,record})=><article className="card" key={`${kind}-${record.id}`}><p><strong>{record.reference}</strong> · Sheets: {record.sheets_sync_status??"PENDING"} · Telegram: {record.notification_status??"NOT REQUIRED"}</p>{record.sheets_sync_error&&<p className="message error">{record.sheets_sync_error}</p>}{record.notification_error&&<p className="message error">{record.notification_error}</p>}<div className="split"><form onSubmit={e=>void retry(e,"/api/integrations/sheets/retry",`${record.reference} synchronized with Sheets.`)}><input type="hidden" name="kind" value={kind}/><input type="hidden" name="reference" value={record.reference}/><button>Retry Sheets</button></form>{record.original_telegram_chat_id&&<form onSubmit={e=>void retry(e,"/api/notifications/retry",`${record.reference} notification delivered.`)}><input type="hidden" name="kind" value={kind}/><input type="hidden" name="reference" value={record.reference}/><button>Retry Telegram</button></form>}</div></article>)}</section>}
